<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MoodRecordController;
use App\Http\Controllers\QuestionnaireController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SharingController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VideoController;
use App\Models\Article;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return response()->json("OK");
});
Route::get('user/bulk/template', [UserController::class, 'getTemplate']);
Route::post('login', [AuthController::class, 'login']);
Route::middleware('auth:api')->group(function () {
    Route::get('me', [AuthController::class, 'me']);
    Route::get('check-username', [AuthController::class, 'checkUsername']);
    Route::get('mood_record/recap/{month}', [MoodRecordController::class, 'recapPerMonth']);
    Route::get('mood_record/check', [MoodRecordController::class, 'check']);
    Route::get('mood_record/today', [MoodRecordController::class, 'today']);
    Route::get('mood_record/streaks', [MoodRecordController::class, 'streaks']);
    Route::get('questionnaire', [QuestionnaireController::class, 'getAllQuestionnaires']);
    Route::get('content', [VideoController::class, 'allContents']);
    Route::get('video/tag/{tag}', [VideoController::class, 'getByaTag']);
    Route::get('article/tag/{tag}', [ArticleController::class, 'getByTag']);
    Route::get('video/{video:video_id}', [VideoController::class, 'getVideoDetailId']);
    Route::get('article/{article:slug}', [ArticleController::class, 'getArticle']);
    Route::get('quote/mood', [QuoteController::class, 'getByType']);
    Route::get('quote/daily', [QuoteController::class, 'getDaily']);
    Route::post('questionnaire/{type}', [QuestionnaireController::class, 'analyzeQuestionnaire'])->whereIn('type', ['secure', 'insecure']);
    Route::post('logout', [AuthController::class, 'logout']);
    Route::post('refresh', [AuthController::class, 'refresh']);
    Route::post('user/bulk', [UserController::class, 'bulkCreate']);
    Route::patch('profile', [UserController::class, 'profile']);
    Route::patch('edit-user/{user:username}', [UserController::class, 'edit']);
    Route::patch('edit-profile', [UserController::class, 'editProfile']);
    Route::delete('user/{user:username}', [UserController::class, 'destroy']);
    Route::apiResource('room', RoomController::class)->only(['index']);
    Route::apiResource('video', VideoController::class)->except(['show']);
    Route::apiResource('article', ArticleController::class)->except(['show']);
    Route::apiResource('quote', QuoteController::class)->except(['update']);
    Route::apiResource('mood_record', MoodRecordController::class)->except(['destroy', 'update']);
    Route::controller(SharingController::class)->group(function () {
        Route::patch('sharing/reply/{sharing}', 'reply');
        Route::post('sharing', 'store');
        Route::get('sharing', 'index');
        Route::get('sharing/{sharing}', 'show');
    });
    Route::controller(ReportController::class)->group(function () {
        Route::patch('report/confirm/{report}', 'confirm');
        Route::patch('report/close/{report}', 'close');
        Route::patch('report/cancel/{report}', 'cancel');
        Route::patch('report/reschedule/{report}', 'reschedule');
        Route::post('report', 'store');
        Route::get('report', 'index');
        Route::get('report/{report}', 'view');
    });
    Route::prefix('dashboard')->group(function () {
        Route::get('headteacher', [DashboardController::class, 'headteacher']);
        Route::get('teacher', [DashboardController::class, 'teacher']);
        Route::get('admin', [DashboardController::class, 'admin']);
        Route::get('counselor', [DashboardController::class, 'counselor']);
        Route::get('student', [UserController::class, 'getStudents']);
        Route::post('users', [UserController::class, 'store']);
        Route::get('users', [UserController::class, 'getUsers']);
        Route::get('users/{username}', [UserController::class, 'getUserDetail']);
        Route::get('users/type/{type}', [UserController::class, 'getUsersByType'])->whereIn('type', ['student', 'teacher', 'counselor', 'headteacher']);
        Route::get('sharing-count', [SharingController::class, 'getSharingCount']);
        Route::get('report-count', [ReportController::class, 'getReportCount']);
        Route::get('room-count', [RoomController::class, 'getRoomCount']);
        Route::get('report-graph', [ReportController::class, 'getReportGraph']);
        Route::get('mood-trends', [MoodRecordController::class, 'getMoodTrend']);
        Route::get('mood-graph', [MoodRecordController::class, 'getMoodGraph']);
        Route::get('latest-content', [VideoController::class, 'getLatestContent']);
        Route::get('latest-user', [UserController::class, 'getLatestUser']);
        Route::get('today-user', [UserController::class, 'getTodayUser']);
        Route::get('today-content', [VideoController::class, 'getTodayContent']);
        Route::get('content', [DashboardController::class, 'content']);
    });
    Route::get('mood-record/pattern/{user:username}/{type}', [MoodRecordController::class, 'moodHistory'])->whereIn('type', ['monthly', 'weekly']);
});
Route::get('tag', [TagController::class, 'index']);
